/* eslint no-unused-vars: off */
/* eslint no-global-assign: off */
/* global systemDictionary */
/*
+===================== DO NOT MODIFY ======================+
| This file was generated by translate-adapter, please use |
| `translate-adapter adminLanguages2words` to update it.   |
+===================== DO NOT MODIFY ======================+
*/
"use strict";

systemDictionary = {
    "pro-vis adapter settings": {
        "en": "Adapter settings for pro-vis",
        "de": "Adaptereinstellungen für pro-vis",
        "ru": "Настройки адаптера для pro-vis",
        "pt": "Configurações do adaptador para pro-vis",
        "nl": "Adapterinstellingen voor pro-vis",
        "fr": "Paramètres d'adaptateur pour pro-vis",
        "it": "Impostazioni dell'adattatore per pro-vis",
        "es": "Ajustes del adaptador para pro-vis",
        "pl": "Ustawienia adaptera dla pro-vis",
        "zh-cn": "pro-vis的适配器设置"
    },
    "option1": {
        "en": "option1",
        "de": "Option 1",
        "ru": "Опция 1",
        "pt": "Opção 1",
        "nl": "Optie 1",
        "fr": "Option 1",
        "it": "opzione 1",
        "es": "Opción 1",
        "pl": "opcja 1",
        "zh-cn": "选项1"
    },
    "option2": {
        "en": "option2",
        "de": "Option 2",
        "ru": "вариант 2",
        "pt": "opção 2",
        "nl": "Optie 2",
        "fr": "Option 2",
        "it": "opzione 2",
        "es": "opcion 2",
        "pl": "Opcja 2",
        "zh-cn": "选项2"
    },
    "myColor": {
        "en": "myColor",
        "de": "meineColor",
        "ru": "Мой цвет",
        "pt": "minhaCor",
        "nl": "mijnKleur",
        "fr": "maCouleur",
        "it": "mioColore",
        "es": "miColor",
        "pl": "mójKolor",
        "zh-cn": "我的颜色"
    },
    "myColor_tooltip": {
        "en": "Description of\nmyColor",
        "de": "Beschreibung von\nmyColor",
        "ru": "Описание\nmyColor",
        "pt": "Descrição de\nmyColor",
        "nl": "Beschrijving van\nmyColor",
        "fr": "Description de\nmyColor",
        "it": "Descrizione di\nmyColor",
        "es": "Descripción de\nmyColor",
        "pl": "Opis\nmyColor",
        "zh-cn": "\nmyColor的描述"
    },
    "htmlText": {
        "en": "htmlText",
        "de": "htmlText",
        "ru": "htmlText",
        "pt": "htmlText",
        "nl": "htmlText",
        "fr": "htmlText",
        "it": "htmlText",
        "es": "htmlText",
        "pl": "htmlText",
        "zh-cn": "htmlText"
    },
    "group_extraMyset": {
        "en": "extraMyset",
        "de": "extraMyset",
        "ru": "extraMyset",
        "pt": "extraMyset",
        "nl": "extraMyset",
        "fr": "extraMyset",
        "it": "extraMyset",
        "es": "extraMyset",
        "pl": "extraMyset",
        "zh-cn": "extraMyset"
    },
    "extraAttr": {
        "en": "extraAttr",
        "de": "extraAttr",
        "ru": "extraAttr",
        "pt": "extraAttr",
        "nl": "extraAttr",
        "fr": "extraAttr",
        "it": "extraAttr",
        "es": "extraAttr",
        "pl": "extraAttr",
        "zh-cn": "extraAttr"
    },
    "Instance": {
        "en": "Instance",
        "de": "Instanz",
        "ru": "Инстанция",
        "pt": "Instância",
        "nl": "Instantie",
        "fr": "Instance",
        "it": "Esempio",
        "es": "Instancia",
        "pl": "Instancja",
        "zh-cn": "例"
    }
};